<!-- ÁREA DE CADASTRO -->
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <!-- FORMULÁRIO DE CADASTRO -->
            <form action="/registrar" method="post">
              <div class="form-group">
                <input value="<?= $this->view->nome ?>" type="text" name="nome" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input value="<?= $this->view->email ?>" type="text" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input value="<?= $this->view->senha ?>" type="password" name="senha" class="form-control" placeholder="Senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
            </form>

            <!-- ERROS DE CADASTRO -->
            <?php if ($this->view->erro == 'erro1') { ?>
            <div class="text-danger d-flex justify-content-center">
              <p>Preencha todos os campos com pelo menos 3 caracteres</p>
            </div>
            <?php } ?>

            <?php if ($this->view->erro == 'erro2') { ?>
            <div class="text-danger d-flex justify-content-center">
              <p>Email já cadastrado</p>
            </div>
            <?php } ?>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  