<!-- BARRA DE NAVEGAÇÃO -->
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<!-- CONTEÚDO DA PAG -->
<div class="container mt-5">
	<div class="row pt-2">
		
		<!-- INFORMAÇÕES DO USUÁRIO -->
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->tweets_usuário ?> </span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->seguidores_usuario ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->usuario_seguindo ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<!-- POSTA TWEET -->
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/inserir_tweet" method="post">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!-- EXIBE TWEETS -->
			<?php foreach ($this->view->tweets as $key => $tweet) { ?>
			<div class="row tweet">
				<div class="col">
					<p><strong><?= $tweet['nome'] ?></strong> <small class="text text-muted"><?= $tweet['data'] ?></small></p>
					<p><?= $tweet['tweet'] ?></p>

					<br />
					
					<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
					<form>
						<div class="col d-flex justify-content-end">
							<a href="/remover_tweet?id=<?= $tweet['id'] ?>" type="submit" class="btn btn-danger"><small>Remover</small></a>
						</div>
					</form>
					<?php } ?>

				</div>
			</div>
			<?php } ?>

			<!-- ÁREA DE NAVEGAÇÃO -->
			<nav aria-label="Page navigation example" class="row mt-4 d-flex justify-content-center">
				<ul class="pagination">
					<li class="page-item">
						<a class="page-link" href="/timeline?pagina=1">Primeira</a>
					</li>

					<?php for ($i=1; $i <= $this->view->total_de_paginas; $i++) { ?>
					<li class="page-item">
						<a class="page-link" href="/timeline?pagina=<?= $i ?>"> <?= $i ?> </a>
					</li>
					<?php } ?>

					<li class="page-item">
						<a class="page-link" href="/timeline?pagina=<?= $this->view->total_de_paginas ?>">Última</a>
					</li>
				</ul>
			</nav>

		</div>

		<!-- MENU LATERAL DIREITO -->
		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>